const fs = require("fs");
const path = require("path");
const { exec } = require("child_process");
const Transaction = require("../models/Transaction");

// GET ALL TRANSACTIONS
const getTransactions = async (req, res) => {
  try {
    const transactions = await Transaction.find({ userId: req.userId }).limit(100);
    res.json(transactions);
  } catch (error) {
    console.error(error);
    res.status(500).json({
      message: "Server Error"
    });
  }
};

// SIMULATE TRANSACTION IN REAL-TIME
const simulateTransaction = async (req, res) => {
  try {
    const { sender, receiver, amount, commit } = req.body;

    if (!sender || !receiver || !amount) {
      return res.status(400).json({ message: "Sender, receiver, and amount are required." });
    }

    // Retrieve existing transactions for the active user
    const existing = await Transaction.find({ userId: req.userId });

    // Generate unique transaction ID for the mock/simulated transaction
    const simTxId = `SIM-${Date.now().toString(36).toUpperCase()}-${Math.floor(Math.random() * 1000)}`;

    // Create the simulated transaction object
    const simulatedTx = {
      transactionId: simTxId,
      amount: String(amount),
      sender: String(sender).trim(),
      receiver: String(receiver).trim()
    };

    // Combine existing transactions with the new simulated transaction
    const combined = [
      ...existing.map(tx => ({
        transactionId: tx.transactionId,
        amount: tx.amount,
        sender: tx.sender,
        receiver: tx.receiver
      })),
      simulatedTx
    ];

    // Write to a temporary CSV file
    const tempFileName = `sim_${req.userId}_${Date.now()}.csv`;
    const tempFilePath = path.join(__dirname, "../uploads", tempFileName);

    const headers = ["transactionId", "amount", "sender", "receiver"];
    const rows = combined.map(tx => [
      tx.transactionId,
      tx.amount,
      tx.sender,
      tx.receiver
    ].map(val => `"${String(val || "").replace(/"/g, '""')}"`).join(","));
    const csvContent = [headers.join(","), ...rows].join("\n");

    // Ensure uploads directory exists
    const uploadsDir = path.dirname(tempFilePath);
    if (!fs.existsSync(uploadsDir)) {
      fs.mkdirSync(uploadsDir, { recursive: true });
    }

    await fs.promises.writeFile(tempFilePath, csvContent, "utf8");

    // Resolve path to the GNN pipeline script
    const scriptPath = path.resolve(__dirname, "../../run_pipeline.py");
    const command = `python "${scriptPath}" "${tempFilePath}"`;

    exec(command, async (error, stdout, stderr) => {
      if (error) {
        console.error(`Simulation ML Pipeline error: ${error.message}`);
        console.error(`stderr: ${stderr}`);
        try {
          fs.unlinkSync(tempFilePath);
        } catch (err) {}
        return res.status(500).json({
          message: "Simulation pipeline execution failed",
          error: error.message
        });
      }

      try {
        const resultsPath = `${tempFilePath}_results.json`;

        if (!fs.existsSync(resultsPath)) {
          throw new Error("Results JSON was not generated by simulation pipeline.");
        }

        // Read and parse results
        const rawResults = await fs.promises.readFile(resultsPath, "utf8");
        const results = JSON.parse(rawResults);

        // Cleanup temporary files
        try {
          fs.unlinkSync(resultsPath);
          fs.unlinkSync(tempFilePath);
        } catch (cleanupError) {
          console.warn("Simulation file cleanup warning:", cleanupError.message);
        }

        if (commit === true) {
          // Commit results permanently to DB by deleting current ones and inserting new ones
          await Transaction.deleteMany({ userId: req.userId });
          const resultsWithUser = results.map(item => ({
            ...item,
            userId: req.userId
          }));
          await Transaction.insertMany(resultsWithUser);
        }

        res.json({
          message: commit ? "Simulation committed to database" : "Simulation run completed",
          transactions: results,
          simulatedId: simTxId
        });

      } catch (parseError) {
        console.error(`Simulation output parse error: ${parseError.message}`);
        try {
          fs.unlinkSync(tempFilePath);
        } catch (err) {}
        res.status(500).json({
          message: "Failed to parse simulation results",
          error: parseError.message
        });
      }
    });

  } catch (error) {
    console.error("Simulation endpoint error:", error);
    res.status(500).json({ message: "Server Error during simulation" });
  }
};

module.exports = {
  getTransactions,
  simulateTransaction
};