const fs = require("fs");

const csv = require("csv-parser");

const xlsx = require("xlsx");

const Transaction =
  require("../models/Transaction");

const { exec } = require("child_process");
const path = require("path");

const uploadFile =
  async (req, res) => {

    try {

      if (!req.file) {

        return res.status(400)
          .json({
            message:
              "No file uploaded"
          });

      }

      const filePath =
        req.file.path;

      const fileName =
        req.file.originalname;

      // Check file extension
      if (
        !fileName.endsWith(".csv") &&
        !fileName.endsWith(".xlsx") &&
        !fileName.endsWith(".xls")
      ) {
        try {
          fs.unlinkSync(filePath);
        } catch (err) {}
        return res.status(400)
          .json({
            message:
              "Only CSV and Excel files allowed"
          });
      }

      // Resolve path to the pipeline script
      const scriptPath = path.resolve(__dirname, "../../run_pipeline.py");

      // Build execution command
      const command = `python "${scriptPath}" "${filePath}"`;

      exec(command, async (error, stdout, stderr) => {
        if (error) {
          console.error(`ML Pipeline error: ${error.message}`);
          console.error(`stderr: ${stderr}`);
          try {
            fs.unlinkSync(filePath);
          } catch (err) {}
          return res.status(500).json({
            message: "ML Pipeline execution failed",
            error: error.message
          });
        }

        try {
          // Output JSON is written by Python to filePath + "_results.json"
          const resultsPath = `${filePath}_results.json`;

          if (!fs.existsSync(resultsPath)) {
            throw new Error("Results JSON file was not generated by ML pipeline.");
          }

          // Read and parse results
          const rawResults = await fs.promises.readFile(resultsPath, "utf8");
          const results = JSON.parse(rawResults);

          // Clean up results file and uploaded sheet file
          try {
            fs.unlinkSync(resultsPath);
            fs.unlinkSync(filePath);
          } catch (cleanupError) {
            console.warn("Temporary file cleanup warning:", cleanupError.message);
          }

          // Reset transaction list and save actual prediction outputs
          await Transaction.deleteMany({ userId: req.userId });
          const resultsWithUser = results.map(item => ({
            ...item,
            userId: req.userId
          }));
          await Transaction.insertMany(resultsWithUser);

          res.json({
            message: "Data analyzed by ML models successfully",
            totalTransactions: results.length
          });

        } catch (parseError) {
          console.error(`ML output parse error: ${parseError.message}`);
          try {
            fs.unlinkSync(filePath);
          } catch (err) {}
          res.status(500).json({
            message: "Failed to parse ML results",
            error: parseError.message
          });
        }
      });

    } catch (error) {

      console.log(error);

      res.status(500).json({

        message:
          "Server Error"

      });

    }

};

module.exports = {
  uploadFile
};